### ISSUE TITLE
bagaimana cara memperbaiki ini fileSha256: "+Ia+Dwib70Y1CWRMAP9QLJKjIJt54fKycOfB2OEZbTU=",               ^^^^^^^^^^

### ISSUE THREAD

**Issue by Ciel-chann** [inirey/whatsapp-bot#9]
ERZA-WHATSAPP@1.0.0 start
> node main

/data/data/com.termux/files/home/whatsapp-bot-main/rey.js:552
              fileSha256: "+Ia+Dwib70Y1CWRMAP9QLJKjIJt54fKycOfB2OEZbTU=",
              ^^^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/data/data/com.termux/files/home/whatsapp-bot-main/main.js:18:1)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)

**Comment by inirey** [comment]
Download 

https://www.mediafire.com/file/vdrakrcs842bf9b/erza.zip/file
